# -*- coding: utf-8 -*-
"""grocerystore.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIdXa4h-rOz3CwEjXoPhG3S9HdIBTDuB
"""

# Grocery Store Calculator

# Declaring variables
grocery_list = []
total_amount = 0

while True:
    print("1. Add Items")
    print("2. Show Bill")
    print("3. Exit")
    choice = int(input("Enter your choice: "))

    if choice == 1:
        num_items = int(input("Enter number of items: "))
        for _ in range(num_items):
            item_name = input("Enter item name: ")
            price = float(input("Enter price per unit: "))
            quantity = int(input("Enter quantity: "))
            total_price = price * quantity
            grocery_list.append((item_name, price, quantity, total_price))
        print("Items added successfully!\n")

    elif choice == 2:
        print("---------------------------------------")
        print("Item	Price	Quantity	Total")
        print("---------------------------------------")
        total_amount = 0
        for item_name, price, quantity, total_price in grocery_list:
            print(f"{item_name}\t{price}\t{quantity}\t{total_price}")
            total_amount += total_price
        print("---------------------------------------")
        print(f"Total Amount: Rs. {total_amount}")
        print("---------------------------------------\n")

    elif choice == 3:
        print("Thank you for using the Grocery Store Calculator!")
        break

    else:
        print("Invalid choice! Please try again.\n")